### PR TITLE
Fix compression

### LINKED ISSUE #31: Remove SNAPPY compression by default
In some broker versions/client runtimes SNAPPY compression can lead to issues (e.g. https://issues.apache.org/jira/browse/KAFKA-3789)

We should remove this default and let users to define this via overrides.

### PR DESCRIPTION
**Pull request by jeqo**
Fixes #31

### CODE REVIEW

File: storage/src/main/java/zipkin2/storage/kafka/KafkaSpanStore.java [hunk 1]
```diff
@@ -111,7 +111,10 @@
 
     @Override public List<String> query() {
       List<String> serviceNames = new ArrayList<>();
-      serviceStore.all().forEachRemaining(keyValue -> serviceNames.add(keyValue.value));
+      serviceStore.all().forEachRemaining(keyValue -> {
+        //if (!serviceNames.contains(keyValue.value)) serviceNames.add(keyValue.value);
```
Comment (jeqo) [inline storage/src/main/java/zipkin2/storage/kafka/KafkaSpanStore.java]: Removing this once validated that it's not receiving same values multiple times

**Comment by adriancole** [comment]
thanks!
